name: CI

on:
  push:
  pull_request:

jobs:
  syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Emacs
        run: |
          sudo apt-get update
          sudo apt-get install --yes emacs-nox
      - name: Parse layer files
        run: emacs -Q --batch -l test/check-syntax.el
